### ISSUE TITLE
Running 'pip install snmpsim' with python2.6 installs snmpsim for python3.5

### ISSUE THREAD

**Issue by rhagman** [etingof/snmpsim#5] opened 2016-11-08 13:06 UTC
Hi!

I'm having problems installing snmpsim with python2.6.6, when I was using pip 1.3 is worked perfectly since it fetched the egg files but now when I'm using a newer version of pip it tries to use the wheel file. I had a look at pypi https://pypi.python.org/pypi/snmpsim/0.3.0 and found that the Py Version states 3.5 when I think it should be py2.py3.

I think this is the same problem described here: http://stackoverflow.com/questions/30438216/how-do-i-upload-a-universal-python-wheel-for-python-2-and-3

Have a nice day!

**Comment by etingof** [comment] 2016-11-11 22:16
> I had a look at pypi https://pypi.python.org/pypi/snmpsim/0.3.0 and found that the Py Version
>  states 3.5 when I think it should be py2.py3.

So it looks to me that the file itself is named properly on PyPI - `snmpsim-0.3.0-py2.py3-none-any.whl`. The only confusing place is PyPI HTML page where (otherwise universal) wheel is marked as belonging to version 3.5. Do you think this causes problems?

I just checked -- I can't manually edit that version number at PyPI, I can only bump simulator version and push it as a new release.

The SO question you linked seems a bit different -- they had wheel file named differently.

How do I replicate the issue you experience? I'm running modern pip (versions 7 and 9) under Python 2.6 and installation works for me.

Please, advise. Thank you!

**Comment by rhagman** [comment] 2016-11-14 10:50
I installed snmpsim on centos6 with python 2.6.6 and pip 7.1.0 in a docker container.

I verified that I indeed got snmpsim-0.3.0-py2.py3-none-any.whl as you said, the problem for me seems to be the shebang in `/usr/bin/snmpsimd.py` where it says `#!/usr/local/bin/python3.5`. This becomes a problem for me when executing snmpsim via scripts.

Thanks for the quick response and also thank you for making snmpsim I think it is awesome!

**Comment by dkindel** [comment] 2017-01-20 14:24
I can confirm this also happens with python 2.7.5 on centos7 and pip 8.1.2 and 9.0.1.  My workaround is modifying that shebang you mentioned to the path of my python binary.  Seems to work okay after that.  

Pretty simple replication: spin up a vagrant centos box and yum install python2 and pip and then attempt a pip install.  If you go into the file `/usr/bin/snmpsimd.py`, you'll see the shebang.

**Comment by etingof** [comment] 2017-01-21 10:37
Alright, I think it's a weird packaging issue. If I do wheel prior to err, than the evil shebang expansion does not occur. Let's see if it works in the [new release](https://pypi.python.org/pypi/snmpsim/0.3.1)?

**Closed by etingof** 2017-01-21 10:37 UTC
